### ISSUE TITLE
Project doesn't open in Unity

### ISSUE THREAD

**Issue by LinuxUserGD** [LuigisMansion/Super-Mario-64-HD-Remake#1]
using Unity 2018.3
Arch Linux

**Comment by MarcioVitor** [comment]
You needs **Visual Studio**, Installed, to open this project !, I use the VS 2017 with the Unity Extension, and works perfectly

**Comment by LinuxUserGD** [comment]
@MarcioVitor I can open the project itself but no main scene is defined. I can browse through the assets using Unity.

**Comment by MarcioVitor** [comment]
Strange, here works normal, without errors, opens the scene with all the resources, as I said you have to have ** Visual Studio ** installed, because when you open the solution, it will redirect to the main scene in Unity

**Comment by LinuxUserGD** [comment]
I get this errors with Unity 2018.3.6f1 on Linux (I'm using Visual Studio Code):
```
[RPGMesh] No MeshFilter.sharedMesh object found
UnityEngine.Debug:Log(Object)
RPGMesh:Start() (at Assets/SuperCharacterController/RPGController/RPGMesh.cs:24)

The animation state idle could not be played because it couldn't be found!
Please attach an animation clip with the name 'idle' or call this function only for existing animations.
UnityEngine.Animation:Play(String)
BobOmbMachine:Idle_EnterState() (at Assets/Mario64HD/Scripts/Actors/BobOmbMachine.cs:135)
SuperStateMachine:ConfigureCurrentState() (at Assets/SuperCharacterController/Core/SuperStateMachine.cs:66)
SuperStateMachine:set_currentState(Enum) (at Assets/SuperCharacterController/Core/SuperStateMachine.cs:39)
BobOmbMachine:Start() (at Assets/Mario64HD/Scripts/Actors/BobOmbMachine.cs:44)

NullReferenceException: Object reference not set to an instance of an object
MarioMachine.Start () (at Assets/Mario64HD/Scripts/Mario/MarioMachine.cs:72)

MissingComponentException: There is no 'Animation' attached to the "koopaQuick" game object, but a script is trying to access it.
You probably need to add a Animation to the game object "koopaQuick". Or your script needs to check if the component is attached before using it.
UnityEngine.Animation.CrossFade (System.String animation, System.Single fadeLength) (at /home/builduser/buildslave/unity/build/artifacts/generated/bindings_old/common/Animation/AnimationsBindings.gen.cs:321)
koopaMachine.Wander_EnterState () (at Assets/New Scripts/koopaMachine.cs:149)
SuperStateMachine.ConfigureCurrentState () (at Assets/SuperCharacterController/Core/SuperStateMachine.cs:66)
SuperStateMachine.set_currentState (System.Enum value) (at Assets/SuperCharacterController/Core/SuperStateMachine.cs:39)
koopaMachine.Start () (at Assets/New Scripts/koopaMachine.cs:42)

Art trans destroyed
UnityEngine.Debug:Log(Object)
redCoin:Update() (at Assets/New Scripts/redCoin.cs:34)

0
UnityEngine.MonoBehaviour:print(Object)
GameMaster:Update() (at Assets/Mario64HD/Scripts/UI/GameMaster.cs:101)

Particle System is trying to spawn on a mesh with zero surface area
```

**Comment by MarcioVitor** [comment]
Your project should be corrupted try cloning the GIT repository on your Linux again or download it in zip, there are also those architectural and system divergences, the project was done for ** Windows **, try to review the manifest files and I am using Windows 10 x64 1809 and it is working, if it does not work even try to do dualboot with ** Windows ** and run the project with visual studio and Unity installed, I'm sure it is not working because of the system , since it shows errors related to model redemption and animations, but before doing all that I said, install the XNA Microsoft Game Studio, and try to compile the project, in case it sucks, install the latest versions of the Direct X SDK and the OpenGLES SDK

**Comment by LinuxUserGD** [comment]
In Unity 2019.1.0f2 on Windows 10 I only get some warnings but again the screen is just blue when I run the game.

**Comment by MarcioVitor** [comment]
The project posted in Github is corrupted, it took me a long time to find one that is not bad, if you want I can post to Github and send you a link, after I have analyzed this project from here we are commenting, it is bad, what I'm going to send you only works with the Unity 5 line, it can be any Unity 5 or 5.6.7f1 or 5.3.4 and others see
